version: '2.2'
services:
  elasticsearch:
    image: elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: kibana:6.6.0
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch

  script:
    build: .
    container_name: script
    stdin_open: true
    tty: true
    command: sh
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    volumes:
      - "./:/var/app"
    networks:
      - esnet
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local

networks:
  esnet:
